### ISSUE TITLE
Disable search filter

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-single-select#1]
Hi,
is it possible to disable the search filter?

Actually I haven't found anything which might help in the README.

**Comment by kuraydev** [comment]
Actually, I need this feature too :D I will add it possibly tomorrow

**Comment by kuraydev** [comment]
Oh you have a PR for that, let me check and test it

**Comment by mariomurrent-softwaresolutions** [comment]
Uh that's nice 😎
Check it, but if it does not fit feel free to move it to the basket 🤪

BTW., really awesome work 😎😎

**Comment by kuraydev** [comment]
Ah thank you for kind words :) I reviewed it, can you check it? I love to merge your PR

**Comment by mariomurrent-softwaresolutions** [comment]
Done and thx for the merge
