### ISSUE TITLE
Add more props to the Arrow image

### ISSUE THREAD

**Issue by ameenmattar** [WrathChaos/react-native-single-select#11]
**Thank you for this awesome plugin!**
### Is it possible to add more props like: 

- Image component that overrides the Arrow image.
- Change the animation for the arrow image.
- A prop to disable the animation or not for the arrow Image.

**Comment by kuraydev** [comment]
Hello @ameenmattar 
Nice request and thank you so much for your kind words :) 

I will think about the requests :) Always PR's are welcome

**Comment by melihmuratpesmen** [comment]
Great work! 💯💯 @WrathChaos 
**New feature idea**:
Icon components support for items

**Comment by kuraydev** [comment]
@melihmuratpesmen 
There is already an icon component feature
ImageComponent is the right prop for that.

**Comment by nico0409** [comment]
amazing work ,
it's great
