### ISSUE TITLE
support for underlay color

### ISSUE THREAD

**Issue by Zhet1** [WrathChaos/react-native-single-select#15]
i see the library and only is add 3 lines of code 

RNSingleSelect.d.ts 
![image](https://user-images.githubusercontent.com/13082170/170785696-d49f5813-46eb-4d24-bead-80e29fe86f7d.png)

and RNSingleSelect.js
![image](https://user-images.githubusercontent.com/13082170/170785886-ffa6dc11-e829-44ae-81cb-b8787a3adaf4.png)

both files are in the build folder of the library

**Comment by kuraydev** [comment]
Hello @Zhet1 
Since you already implement it, can you please open a PR for this?
