### ISSUE TITLE
support for nestedscrollenabled property

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-single-select#18]
In order to make nested scrolling on Android possible we need to enable nestedscrollenabled for the scrollview

**Comment by kuraydev** [comment]
#19 merged, I will publish a new version today :) 

Thank you for the contribution

**Comment by mariomurrent-softwaresolutions** [comment]
Thank you very much

**Comment by kuraydev** [comment]
https://github.com/WrathChaos/react-native-single-select/releases/tag/1.0.0

Version 1 is released :)
