### ISSUE TITLE
Set initial value

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-single-select#2]
Hi,
is it possible to set the initial value?

Actually I haven't found anything which might help in the README.

**Comment by kuraydev** [comment]
I can make it this week :)

**Comment by mariomurrent-softwaresolutions** [comment]
Sure, no stress ... maybe I will also give it a hands on session :)

**Comment by mariomurrent-softwaresolutions** [comment]
Done by #4
