### ISSUE TITLE
Strange behaviour when two single select are visible in the same view

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-single-select#5]
When I have two Single Selects on the same view the behaviour is strange. The toggle buttons are changed, but on the wrong single select.

[See it in action](https://www.meecode.at/customers/git/RPReplay_Final1614067115.mov)

This happens both on iOS and Android

**Comment by kuraydev** [comment]
I think this happens because these are functional components. I think wrapping the RNSingleSelect with PureComponent should fix the problem. I need to test it.

**Comment by mariomurrent-softwaresolutions** [comment]
Is there any update on this? :) Otherwise I can also have a look at it

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions If you have time, please take a look. I could not spare time for now

**Comment by mariomurrent-softwaresolutions** [comment]
Sure 😊

**Comment by kuraydev** [comment]
New version is released :) 
### [Version 0.3.9](https://github.com/WrathChaos/react-native-single-select/releases/tag/0.3.9)

Thank you so much @mariomurrent-softwaresolutions
