### ISSUE TITLE
Improvement: Readonly State touchable

### ISSUE THREAD

**Issue by kuraydev** [WrathChaos/react-native-single-select#6]
ReadOnly state is not touchable on the text input part

**Comment by mariomurrent-softwaresolutions** [comment]
@WrathChaos So 0.3.3 also includes all the other pull requests?

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions yes, they are. Can you test it if possible?

**Comment by mariomurrent-softwaresolutions** [comment]
Working like a charm :) Also with the touchable opacity fix. Perfect.
