### ISSUE TITLE
Option for Expo please (no spinkit)

### ISSUE THREAD

**Issue by Noitidart** [WrathChaos/react-native-single-select#7]
Hi there,

Spinkit is used just for the spin animation of the arrow is this true? I was hoping to use this in Expo, so we can't install custom native modules. Is it possible to request a quick and dirty expo option? 

And then for long term i can help you rewrite the animations in reanimated, expo has v1. And will have v2 soon.

**Comment by kuraydev** [comment]
Hello, 
Sure I will make it an expo version today :) I will inform you ASAP

**Comment by Noitidart** [comment]
Thank you brother that is way too kind of you! I will also help asap to use reanimated for whatever you were using spinkit for! If you can guide me there when you have time afterwords I will hook it up. Maybe i can pr to allow people to use custom spinners too!

**Comment by mariomurrent-softwaresolutions** [comment]
@Noitidart I'm using this library in Expo without any errors.

**Comment by Noitidart** [comment]
> @Noitidart I'm using this library in Expo without any errors.

Oh thank you Mario! I must have done something silly I will try it again now!

**Comment by mariomurrent-softwaresolutions** [comment]
What kind of error do you get?

**Comment by Noitidart** [comment]
I get this error, screenshot below. Thanks for asking!

I think the spinner is only shown while data is an empty array.

Here is a snack - https://snack.expo.io/@noitidart/react-native-single-select

```
export default function App() {
  const staticData: Array<ISingleSelectDataType> = [
    { id: 0, value: 'Euismod Justo' },
    { id: 1, value: 'Risus Venenatis' },
    { id: 2, value: 'Vestibulum Ullamcorper' },
    { id: 3, value: 'Lorem Nibh' },
    { id: 4, value: 'Ligula Amet' },
  ];

  return (
    <View style={styles.container}>
      <RNSingleSelect
        data={staticData}
        darkMode
        onSelect={(selectedItem: ISingleSelectDataType) =>
          console.log('SelectedItem: ', selectedItem)
        }
      />
    </View>
  );
}
```

<img width="437" alt="image" src="https://user-images.githubusercontent.com/6372489/110373607-85ec1c00-8004-11eb-99dd-65b66f31c9bd.png">

**Comment by mariomurrent-softwaresolutions** [comment]
Well you just need to install the spinkit package 😊 then it will work. 
As it is in the description of this package spinkit is required for this to work

**Comment by Noitidart** [comment]
Oh I didnt realize we can install it but not link it, and it will work. Thanks! I will try.

Edit: Yes! It works! Thank you!!

**Comment by mariomurrent-softwaresolutions** [comment]
Perfekt - so the issue can be closed @WrathChaos

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions Thank you man!

lol I did not know that spinkit is usable on Expo :D Nice to know

**Comment by Noitidart** [comment]
I think spinkit is not usable on expo. Has anyone verified?  I will try. But spinkit is not linked so it will crash if it tries to render it. So the tip is to not have empty array.

**Comment by mariomurrent-softwaresolutions** [comment]
> I think spinkit is not usable on expo. Has anyone verified? I will try. But spinkit is not linked so it will crash if it tries to render it. So the tip is to not have empty array.

I'm using it in my managed expo app, at least the dependency is installed and everything works fine

**Comment by Noitidart** [comment]
Oh wow no way. Ill have to try that. Thanks!

**Comment by mariomurrent-softwaresolutions** [comment]
As I already wrote before, I'm using react-native-single-select in my expo and without any errors.
