### ISSUE TITLE
Dynamically change value

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-single-select#8]
It would be nice to change the selected item dynamically. 
Initial value is set, when the control is initialized, but can never be changed from a e.g. state update

**Comment by mariomurrent-softwaresolutions** [comment]
PR for that is open :)

**Comment by kuraydev** [comment]
Hello @mariomurrent-softwaresolutions,
Lovely work! Thank you so much. 

Here is the new version: 

## [Release 0.3.4 🥳](https://github.com/WrathChaos/react-native-single-select/releases/tag/0.3.4)

**Comment by mariomurrent-softwaresolutions** [comment]
@WrathChaos Seems like there is something wrong with the build.
The changes are not reflected for the selectedItem

In the dist folder in the RNSingleSelect.js I can see:

React.useEffect(() => { if (darkMode) setTheme(theme_1.DARK); else setTheme(theme_1.LIGHT); }, []);

But there are two lines missing:

setSelectedItem(initialValue); setPlaceholderText(placeholder);

Actually I don't know if this has been thrown out by the compiler?

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions Thank you ! Let me rebuild it very fast

**Comment by mariomurrent-softwaresolutions** [comment]
Thanks

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions Can you try `0.3.5` version?

**Comment by mariomurrent-softwaresolutions** [comment]
@WrathChaos Now the code is correct, but I added another PR, because the setter method was in the wrong use effect ...
Sorry my fault :(

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions Can you check the PR again?

**Comment by mariomurrent-softwaresolutions** [comment]
Sure

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions Can you try `0.3.6` version? I will unpublish  0.3.5 version

**Comment by mariomurrent-softwaresolutions** [comment]
Works like a charm, perfect

**Comment by mariomurrent-softwaresolutions** [comment]
@WrathChaos Have you ever thought about creating your own UI library out of the components?

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions I do actually. I already have enough components for a UI Framework. Maybe we can make it together? Wanna discuss it on email?

**Comment by mariomurrent-softwaresolutions** [comment]
@WrathChaos Sure, lets discuss it via E-Mail. I think you already have mine - we have already exchanged some messages
